### PR TITLE
(SERVER-1733) Update to clj-parent 0.4.3 and i18n 0.7.1

### PR DESCRIPTION
**Pull request by camlow325**
This commit updates the clj-parent dependency to 0.4.3 and i18n plugin
dependency to 0.7.1.  This commit also includes some updates to
i18n-related files, including the removal of pot files which are no
longer used, updates to the Makefile, and regenerated .po files.

### CODE REVIEW

**Comment by rlinehan** [comment]
This failed CI with what seems like maybe a race condition?

```
lein test :only puppetlabs.trapperkeeper.services.watcher.filesystem-watch-service-test/multiple-watch-dirs-test

FAIL in (multiple-watch-dirs-test) (filesystem_watch_service_test.clj:308)

Watching of multiple directories using a single watcher Nested watch directories

expected: (= events (wait-for-events results events))

  actual: (not (= #{{:changed-path #object[java.io.File 0x4a5f435b "/tmp/dir-11490046021406-2138734755/nested-dir/test-file"], :type :create} {:changed-path #object[java.io.File 0x6b021959 "/tmp/dir-11490046021406-2138734755/nested-dir"], :type :create}} ({:type :create, :count 1, :watched-path #object[java.io.File 0x175957f9 "/tmp/dir-21490046021406-2586723413"], :changed-path #object[java.io.File 0xccd3e52 "/tmp/dir-21490046021406-2586723413/nested-dir"]} {:type :create, :count 1, :watched-path #object[java.io.File 0x3c38f10b "/tmp/dir-11490046021406-2138734755/nested-dir"], :changed-path #object[java.io.File 0x470bef04 "/tmp/dir-11490046021406-2138734755/nested-dir/test-file"]} {:type :modify, :count 1, :watched-path #object[java.io.File 0x1ab08e83 "/tmp/dir-11490046021406-2138734755/nested-dir"], :changed-path #object[java.io.File 0x7f6a0c29 "/tmp/dir-11490046021406-2138734755/nested-dir/test-file"]})))
```

I'm inclined to just try kicking it and see what happens?

**Comment by camlow325** [comment]
@rlinehan Yeah, we've seen that before.  Race condition related to a JDK bug which comes up once in a while, unfortunately.

**Comment by rlinehan** [comment]
@camlow325 it looks like it failed again :(

**Comment by rlinehan** [comment]
omg it passed! 🎆

**Pull request merged**
